{{- if and .Values.sqlserver.enabled (not (and .Values.argoEvents.enabled .Values.argoEvents.triggerSetupJob)) }}
{{- $root := . }}
{{- range $db := .Values.sqlserver.databases }}
---
{{ include "opentelemetry-database-monitoring.sqlserverSetupJob" (dict "root" $root "db" $db "useName" true "useGenerateName" false "helmHook" true) }}
{{- end }}
{{- end }}
