---
clusterName: test-cluster
agent:
  config:
    service:
      pipelines:
        extraPipelines:
          metrics/extra:
            receivers:
              - host_metrics
            exporters:
              - otlp_http/tsuga
