{{- if and .Values.secret.create (not .Values.secret.existing.enabled) }}
{{- include "opentelemetry-kube-stack.validateSecretValues" . }}
{{- include "opentelemetry-kube-stack.validateResourceNames" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-kube-stack.secretName" . }}
  labels:
    {{- include "opentelemetry-kube-stack.componentLabels" (dict "component" "secret" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
type: Opaque
stringData:
  # Tsuga API key from root configuration
  {{ include "opentelemetry-kube-stack.secretKey" (dict "keyName" "TSUGA_API_KEY" "Values" .Values) }}: {{ .Values.tsuga.apiKey }}
  # Tsuga OTLP endpoint from root configuration
  {{ include "opentelemetry-kube-stack.secretKey" (dict "keyName" "TSUGA_OTLP_ENDPOINT" "Values" .Values) }}: {{ .Values.tsuga.otlpEndpoint }}
{{- end }}
