apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-monitoring-setup
  namespace: {{ include "opentelemetry-demo.namespace" . }}
data:
  monitoring-setup.sql: |
{{ .Files.Get "assets/pg-monitoring-setup.sql" | replace "your-password" "otelmonitor" | indent 4 }}
