---
name: Release Charts

permissions: {}

on:
  push:
    branches:
      - main

env:
  HELM_VERSION: "3.12.0"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Generate release notes (opentelemetry-kube-stack)
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: charts/opentelemetry-kube-stack/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: charts/opentelemetry-kube-stack/release-notes.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate release notes (opentelemetry-demo)
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: charts/opentelemetry-demo/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: charts/opentelemetry-demo/release-notes.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate release notes (tsuga-spicy-gremlin)
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: charts/tsuga-spicy-gremlin/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: charts/tsuga-spicy-gremlin/release-notes.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: ${{ env.HELM_VERSION }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add dependent repositories
        run: |
          helm repo add tsuga-dev https://tsuga-dev.github.io/helm-charts
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          skip_existing: true
          charts_dir: charts
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
